FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14

# Install custom tools, runtimes, etc.
# For example "bastet", a command-line tetris clone:
# RUN brew install bastet
#
# More information: https://www.gitpod.io/docs/config-docker/

ENV PYTHONPATH="/workspace/InteractionFreePy"
